import { modules, badges } from './content.js';
const KEY='queryquest-progress';
const fresh=()=>({xp:0,done:[],answers:{},streak:1,last:new Date().toDateString(),badges:[]});
let state=JSON.parse(localStorage.getItem(KEY)||'null')||fresh();
function updateStreak(){const today=new Date();const todayKey=today.toDateString();if(state.last===todayKey)return;const previous=new Date(state.last);const diff=Math.round((new Date(todayKey)-new Date(previous.toDateString()))/86400000);state.streak=diff===1?state.streak+1:1;state.last=todayKey;localStorage.setItem(KEY,JSON.stringify(state));}
updateStreak();
const allLessons=()=>modules.flatMap(m=>m.lessons);
const save=()=>{localStorage.setItem(KEY,JSON.stringify(state));render();};
const level=()=>state.xp>=1200?5:state.xp>=800?4:state.xp>=450?3:state.xp>=200?2:1;
const levelName=['','Explorador','Consultor SQL','Ferreiro ORM','Guardião das Transações','Arquiteto da SPA'][level()];
const nextXp=[0,200,450,800,1200,1600][level()];
const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');
function nav(){document.querySelector('#module-nav').innerHTML=modules.map((m,i)=>{let done=m.lessons.filter(l=>state.done.includes(l.id)).length;let unlocked=i===0||modules[i-1].lessons.every(l=>state.done.includes(l.id));return `<div class="nav-module ${unlocked?'':'locked'}" data-module="${m.id}"><div class="nav-title"><span class="nav-icon ${m.color}">${m.icon}</span><div><b>${String(i+1).padStart(2,'0')} ${m.title}</b><small>${done}/${m.lessons.length} aulas</small></div><span class="chev">${unlocked?'›':'🔒'}</span></div><div class="nav-progress"><i style="width:${done/m.lessons.length*100}%"></i></div></div>`}).join('');document.querySelectorAll('[data-module]').forEach(x=>x.onclick=()=>{if(!x.classList.contains('locked')) location.hash='#/module/'+x.dataset.module});}
function moduleView(id){let m=modules.find(x=>x.id===id)||modules[0];let unlocked=modules.indexOf(m)===0||modules[modules.indexOf(m)-1].lessons.every(l=>state.done.includes(l.id));return `<section class="content"><div class="eyebrow"><a href="#/">TRILHA</a> / MÓDULO ${String(modules.indexOf(m)+1).padStart(2,'0')}</div><div class="section-head module-view-head"><div><h1>${m.title}</h1><p>${m.desc}</p></div><span class="completion">${m.lessons.filter(l=>state.done.includes(l.id)).length}/${m.lessons.length} concluídas</span></div><div class="lesson-list">${m.lessons.map((l,i)=>`<article class="lesson-row ${state.done.includes(l.id)?'is-done':''} ${unlocked?'':'is-locked'}" data-lesson="${l.id}"><span class="lesson-number">${state.done.includes(l.id)?'✓':String(i+1).padStart(2,'0')}</span><div><span class="tag ${m.color}">${l.tag}</span><h3>${l.title}</h3><small>${l.time} · ✦ ${l.xp} XP</small></div><b>${unlocked?'→':'🔒'}</b></article>`).join('')}</div></section>`}
function dashboard(){let pct=Math.round(state.done.length/allLessons().length*100);let current=allLessons().find(l=>!state.done.includes(l.id))||allLessons().at(-1);return `<section class="content"><div class="eyebrow">BEM-VINDO DE VOLTA, DEV <span class="pulse"></span></div><div class="hero"><div><h1>Seu próximo <em>bug</em><br/>vai virar <em>XP.</em></h1><p>Aprenda SQL e SQLAlchemy construindo algo real,<br class="desktop"/> uma query de cada vez.</p><button class="primary" data-go="${current.id}">Continuar trilha <span>→</span></button></div><div class="hero-orb"><div class="orb-ring"></div><span>⌘</span><small>BUILD<br/>YOUR<br/>QUERY</small></div></div><div class="stats-grid"><div class="stat-card"><span class="stat-icon cyan">↗</span><div><small>PROGRESSO TOTAL</small><strong>${pct}%</strong><div class="line"><i style="width:${pct}%"></i></div></div></div><div class="stat-card"><span class="stat-icon orange">ϟ</span><div><small>XP ACUMULADO</small><strong>${state.xp} <small>/ 1200</small></strong><div class="line orange-line"><i style="width:${Math.min(state.xp/1200*100,100)}%"></i></div></div></div><div class="stat-card"><span class="stat-icon pink">♨</span><div><small>SEQUÊNCIA ATUAL</small><strong>${state.streak} <small>dias</small></strong><span class="sub">Melhor: ${Math.max(state.streak,3)} dias</span></div></div></div><div class="section-head"><div><div class="eyebrow">MAPA DA TRILHA</div><h2>Do primeiro SELECT ao ORM</h2></div><span class="completion">${state.done.length}/${allLessons().length} concluídas</span></div><div class="module-grid">${modules.map((m,i)=>{let open=i===0||modules[i-1].lessons.every(l=>state.done.includes(l.id));let d=m.lessons.filter(l=>state.done.includes(l.id)).length;return `<article class="module-card ${open?'':'is-locked'}" data-module="${m.id}"><div class="module-top"><span class="module-icon ${m.color}">${m.icon}</span><span class="module-status">${d===m.lessons.length?'✓ CONCLUÍDO':open?'MÓDULO '+String(i+1).padStart(2,'0'):'🔒 BLOQUEADO'}</span></div><h3>${m.title}</h3><p>${m.desc}</p><div class="card-footer"><span>${d}/${m.lessons.length} aulas</span><b>${open?'Explorar módulo →':'Complete o anterior'}</b></div></article>`}).join('')}</div><div class="section-head badges-head"><div><div class="eyebrow">CONQUISTAS</div><h2>Badges desbloqueáveis</h2></div><span class="completion">${state.badges.length}/${badges.length}</span></div><div class="badges-grid">${badges.map(b=>`<div class="badge-card ${state.badges.includes(b.id)?'earned':''}"><span>${b.icon}</span><div><b>${b.title}</b><small>${b.desc}</small></div></div>`).join('')}</div></section>`}
function lessonView(id){let l=allLessons().find(x=>x.id===id)||allLessons()[0],m=modules.find(x=>x.lessons.some(y=>y.id===l.id));return `<section class="content lesson-page"><div class="eyebrow"><a href="#/">TRILHA</a> / ${m.title.toUpperCase()}</div><div class="lesson-heading"><div><span class="tag ${m.color}">${l.tag}</span><h1>${l.title}</h1><p>${l.intro}</p></div><div class="lesson-meta"><span>◷ ${l.time}</span><span class="xp-reward">✦ +${l.xp} XP</span></div></div><div class="lesson-layout"><div><div class="code-tabs"><span class="active">SQL</span><span>PYTHON / SQLALCHEMY</span></div><div class="code-block"><div class="code-head"><span><i></i><i></i><i></i></span><small>queryquest / lesson.sql</small><button class="copy" data-copy="${esc(l.code)}">⧉ copiar</button></div><pre>${esc(l.code)}</pre></div><div class="code-block python"><div class="code-head"><small>main.py</small></div><pre>${esc(l.py)}</pre></div></div><aside class="challenge"><div class="challenge-label">⚡ CHECKPOINT</div><h3>Teste seu conhecimento</h3><p>${l.quiz.q}</p><div class="options">${l.quiz.opts.map((o,i)=>`<button class="option" data-answer="${i}">${o}</button>`).join('')}</div><div id="feedback"></div></aside></div><button class="complete ${state.done.includes(l.id)?'completed':''}" data-complete="${l.id}">${state.done.includes(l.id)?'✓ Lição concluída':'Marcar lição como concluída'} <span>${state.done.includes(l.id)?'':'+'+l.xp+' XP'}</span></button></section>`}
function render(){nav();document.querySelector('#xp').textContent=state.xp;document.querySelector('#level').textContent=level();document.querySelector('#streak').textContent=state.streak;let hash=location.hash;let lesson=hash.match(/lesson\/(\w+)/), mod=hash.match(/module\/(\w+)/);document.querySelector('#app').innerHTML=lesson?lessonView(lesson[1]):mod?moduleView(mod[1]):dashboard();document.querySelector('#crumb').textContent=lesson?'LIÇÃO':mod?'MÓDULO':'INÍCIO';bind();}
function bind(){document.querySelectorAll('[data-module]').forEach(x=>x.onclick=()=>{if(!x.classList.contains('is-locked')&&!x.classList.contains('locked'))location.hash='#/module/'+x.dataset.module});document.querySelectorAll('[data-lesson]').forEach(x=>x.onclick=()=>{if(!x.classList.contains('is-locked'))location.hash='#/lesson/'+x.dataset.lesson});document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>location.hash='#/lesson/'+x.dataset.go);document.querySelectorAll('.module-card:not(.is-locked)').forEach(x=>x.onclick=()=>location.hash='#/lesson/'+modules.find(m=>m.id===x.dataset.module).lessons[0].id);document.querySelectorAll('.option').forEach(x=>x.onclick=()=>{document.querySelectorAll('.option').forEach(b=>b.classList.remove('selected','wrong','right'));let l=allLessons().find(x=>location.hash.includes(x.id));let ok=+x.dataset.answer===l.quiz.answer;x.classList.add(ok?'right':'wrong');document.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'good':'bad'}"><b>${ok?'Muito bem! +20 XP':'Quase! Tenta de novo.'}</b><span>${l.quiz.why}</span></div>`;if(ok&&!state.answers[l.id]){state.answers[l.id]=1;state.xp+=20;if(!state.badges.includes('first'))state.badges.push('first');save()} });document.querySelectorAll('[data-complete]').forEach(x=>x.onclick=()=>{if(!state.done.includes(x.dataset.complete)){state.done.push(x.dataset.complete);let l=allLessons().find(y=>y.id===x.dataset.complete);state.xp+=l.xp;toast(`+${l.xp} XP · lição concluída!`);save()} });document.querySelectorAll('[data-copy]').forEach(x=>x.onclick=()=>{navigator.clipboard?.writeText(x.dataset.copy);toast('Query copiada!')});}
function toast(t){let e=document.querySelector('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
document.querySelector('#reset-btn').onclick=()=>{if(confirm('Reiniciar todo o progresso?')){state=fresh();save();}};document.querySelector('#menu-btn').onclick=()=>document.querySelector('#sidebar').classList.toggle('open');window.addEventListener('hashchange',render);render();
