// Conteúdo didático separado da interface: novos módulos podem ser adicionados aqui.
export const modules = [
 {id:'m1', icon:'⌁', color:'cyan', title:'Pensando em dados', subtitle:'Do Python para o banco', desc:'Descubra como suas classes viram tabelas e como os dados se conectam.', lessons:[
  {id:'l11', title:'Da lista Python para uma tabela', tag:'COMECE AQUI', time:'8 min', xp:50, type:'lesson', intro:'Uma lista funciona muito bem enquanto sua agenda cabe na memória. Mas e quando você fecha o programa? O banco entra em cena para guardar tudo.', code:`CREATE TABLE tarefas (\n  id INTEGER PRIMARY KEY,\n  titulo TEXT NOT NULL,\n  feito BOOLEAN DEFAULT FALSE\n);`, py:`class Tarefa(Base):\n    __tablename__ = "tarefas"\n    id = Column(Integer, primary_key=True)\n    titulo = Column(String, nullable=False)\n    feito = Column(Boolean, default=False)`, quiz:{q:'Qual coluna identifica uma tarefa de forma única?', opts:['titulo','feito','id','comentarios'], answer:2, why:'O id é a chave primária: um identificador único para cada registro.'}},
  {id:'l12', title:'Comentários e relações', tag:'FUNDAMENTO', time:'10 min', xp:60, type:'lesson', intro:'A classe ComentarioTarefa representa cada comentário ligado a uma tarefa — “revisar antes da prova”, por exemplo. Isso é uma relação 1 para muitos (1:N).', code:`CREATE TABLE comentarios_tarefa (\n  id INTEGER PRIMARY KEY,\n  tarefa_id INTEGER NOT NULL,\n  conteudo TEXT NOT NULL,\n  FOREIGN KEY (tarefa_id) REFERENCES tarefas(id)\n);`, py:`tarefa_id = Column(\n    Integer,\n    ForeignKey("tarefas.id"),\n    nullable=False\n)`, quiz:{q:'Onde o comentário guarda a ligação com sua tarefa?', opts:['No titulo','Em tarefa_id','No id da tarefa','Em feito'], answer:1, why:'A chave estrangeira tarefa_id aponta para o id da tarefa relacionada.'}}
 ]},
 {id:'m2', icon:'⌕', color:'purple', title:'Consultas SQL', subtitle:'Busque exatamente o que precisa', desc:'SELECT, filtros e consultas que respondem perguntas reais.', lessons:[
  {id:'l21', title:'SELECT: sua primeira busca', tag:'SQL NA PRÁTICA', time:'9 min', xp:70, type:'lesson', intro:'Imagine o app perguntando: “quais tarefas ainda estão pendentes?”. SQL transforma essa pergunta em uma consulta precisa.', code:`SELECT id, titulo, feito\nFROM tarefas;\n\nSELECT * FROM tarefas\nWHERE feito = FALSE;`, py:`comando = select(TarefaModel)\nresult = session.execute(comando)\ntarefas = result.scalars().all()`, quiz:{q:'Qual cláusula filtra registros?', opts:['FROM','WHERE','SELECT','FILTER'], answer:1, why:'WHERE define a condição que um registro precisa cumprir para aparecer.'}},
  {id:'l22', title:'Encontrando uma tarefa', tag:'DESAFIO', time:'10 min', xp:80, type:'lesson', intro:'Para abrir os detalhes da tarefa 3, você precisa encontrar um único registro — e lidar com o caso em que ele não existe.', code:`SELECT * FROM tarefas\nWHERE id = 3;\n\nSELECT * FROM comentarios_tarefa\nWHERE tarefa_id = 3;`, py:`comando = select(TarefaModel).where(\n    TarefaModel.id == id\n)\ntarefa = result.scalar_one_or_none()`, quiz:{q:'O que scalar_one_or_none() pode retornar?', opts:['Sempre uma lista','Um modelo ou None','Sempre um erro','A sessão'], answer:1, why:'Ele retorna um único resultado quando existe, ou None quando não encontra.'}}
 ]},
 {id:'m3', icon:'◈', color:'orange', title:'Forjando o ORM', subtitle:'SQLAlchemy sem mistério', desc:'Conecte classes Python às tabelas do banco e mantenha seu código organizado.', lessons:[
  {id:'l31', title:'Model e domínio são diferentes', tag:'ARQUITETURA', time:'12 min', xp:90, type:'lesson', intro:'No projeto, TarefaModel representa o banco. TarefaClass representa a regra de negócio. Essa separação evita que a tela dependa dos detalhes da persistência.', code:`# model.py → conhece o banco\nclass TarefaModel(Base): ...\n\n# controller.py → conhece regras\nclass Tarefa:\n    def marcar_como_feito(self):\n        if self.feito:\n            raise ValueError("Já concluída")`, py:`nova_tarefa = TarefaClass(\n    titulo=tarefa_modelo.titulo,\n    feito=tarefa_modelo.feito,\n    id=tarefa_modelo.id\n)`, quiz:{q:'Qual classe contém marcar_como_feito()?', opts:['TarefaModel','TarefaClass','ComentarioModel','Base'], answer:1, why:'A regra de negócio vive em TarefaClass, no controller.py.'}},
  {id:'l32', title:'JOIN: conectando histórias', tag:'CONEXÕES', time:'12 min', xp:100, type:'lesson', intro:'Um JOIN reúne a tarefa e seus comentários numa mesma história. É como perguntar: “me conte tudo sobre essa tarefa”.', code:`SELECT t.titulo, c.conteudo\nFROM tarefas t\nLEFT JOIN comentarios_tarefa c\n  ON c.tarefa_id = t.id;`, py:`# evolução conceitual\ntarefa.comentarios`, quiz:{q:'O que representa uma relação 1:N?', opts:['Uma tarefa para um comentário','Várias tarefas para uma tarefa','Uma tarefa para vários comentários','Nenhuma relação'], answer:2, why:'Uma tarefa pode ter N (vários) comentários.'}}
 ]},
 {id:'m4', icon:'↻', color:'green', title:'Transações', subtitle:'Grave com segurança', desc:'INSERT, UPDATE, DELETE e o poder de commit e rollback.', lessons:[
  {id:'l41', title:'Commit ou rollback?', tag:'MÃO NA MASSA', time:'12 min', xp:100, type:'lesson', intro:'Você adicionou uma tarefa, mas ela só existe de verdade quando confirma a transação. Se algo der errado, rollback desfaz o caminho.', code:`INSERT INTO tarefas (titulo, feito)\nVALUES ('Estudar SQL', FALSE);`, py:`session.add(nova_tarefa)\ntry:\n    session.commit()\n    session.refresh(nova_tarefa)\nexcept:\n    session.rollback()`, quiz:{q:'Qual comando confirma uma gravação?', opts:['add()','refresh()','commit()','execute()'], answer:2, why:'commit() confirma a transação e persiste a mudança.'}},
  {id:'l42', title:'A regra de concluir', tag:'REGRA DE NEGÓCIO', time:'10 min', xp:110, type:'lesson', intro:'O botão “Concluir” não deve apenas mudar a tela. Primeiro, a regra do controller verifica se a tarefa já foi concluída.', code:`UPDATE tarefas SET feito = TRUE\nWHERE id = 1;`, py:`if self.feito == True:\n    raise ValueError(\n      "Essa tarefa já está marcada"\n    )\nself.feito = True`, quiz:{q:'Onde deve ficar a regra “não concluir duas vezes”?', opts:['No CSS','No banco apenas','Na regra de negócio','No botão'], answer:2, why:'A regra deve estar no domínio para ser respeitada por qualquer interface.'}}
 ]},
 {id:'m5', icon:'✦', color:'pink', title:'Mini-projeto', subtitle:'Construa o TaskQuest', desc:'Junte tudo: tarefas, comentários, filtros e uma arquitetura limpa.', lessons:[
  {id:'l51', title:'Desafio final: TaskQuest', tag:'PROJETO FINAL', time:'25 min', xp:500, type:'project', intro:'Agora é com você. Planeje uma pequena central de tarefas: liste pendências, conclua tarefas, adicione comentários e trate os erros com mensagens úteis.', code:`# checklist do seu mini-projeto\n1. Listar tarefas\n2. Filtrar por feito\n3. Criar e concluir\n4. Comentar e remover\n5. Tratar tarefas inexistentes`, py:`Tela → serviço → repositório → banco\n\n# controller: regras\n# model: persistência\n# main: orquestração`, quiz:{q:'Qual é o primeiro passo para começar?', opts:['Apagar o model','Listar as tarefas','Ignorar erros','Usar um backend'], answer:1, why:'Comece exibindo os dados: depois evolua para filtros e ações.'}}
 ]}
];
export const badges=[{id:'first',icon:'⚡',title:'Primeiro SELECT',desc:'Completou sua primeira lição'},{id:'streak',icon:'🔥',title:'Constante',desc:'Manteve 3 dias de sequência'},{id:'join',icon:'◈',title:'Mestre do JOIN',desc:'Aprendeu a conectar tabelas'},{id:'finish',icon:'✦',title:'Entrega épica',desc:'Concluiu o mini-projeto'}];
