// Conteúdo didático separado da interface: novos módulos podem ser adicionados aqui.
export const modules = [
 {id:'m1', icon:'⌁', color:'cyan', title:'Pensando em dados', subtitle:'Do Python para o banco', desc:'Descubra como suas classes viram tabelas e como os dados se conectam.', lessons:[
  {id:'l11', title:'Da lista Python para uma tabela', tag:'COMECE AQUI', time:'8 min', xp:50, type:'lesson', intro:'Enquanto o programa está em execução, uma lista Python mantém os dados na memória, mas tudo é perdido ao fechá-lo. Um banco de dados armazena esses dados em disco, organizados em tabelas, garantindo que você possa acessá-los novamente sempre que precisar, mesmo após reiniciar o aplicativo.', code:`CREATE TABLE tarefas (\n  id INTEGER PRIMARY KEY,\n  titulo TEXT NOT NULL,\n  feito BOOLEAN DEFAULT FALSE\n);`, py:`class Tarefa(Base):\n    __tablename__ = "tarefas"\n    id = Column(Integer, primary_key=True)\n    titulo = Column(String, nullable=False)\n    feito = Column(Boolean, default=False)`, quiz:{q:'Qual coluna identifica uma tarefa de forma única?', opts:['titulo','feito','id','comentarios'], answer:2, why:'O id é a chave primária: um identificador único para cada registro.'}},
  {id:'l12', title:'Comentários e relações', tag:'FUNDAMENTO', time:'10 min', xp:60, type:'lesson', intro:'A classe ComentarioTarefa representa cada comentário ligado a uma tarefa — “revisar antes da prova”, por exemplo. Isso é uma relação 1 para muitos (1:N): Uma única tarefa pode ter vários comentários, mas cada comentário pertence a apenas uma tarefa.', code:`CREATE TABLE comentarios_tarefa (\n  id INTEGER PRIMARY KEY,\n  tarefa_id INTEGER NOT NULL,\n  conteudo TEXT NOT NULL,\n  FOREIGN KEY (tarefa_id) REFERENCES tarefas(id)\n);`, py:`tarefa_id = Column(\n    Integer,\n    ForeignKey("tarefas.id"),\n    nullable=False\n)`, quiz:{q:'Onde o comentário guarda a ligação com sua tarefa?', opts:['No titulo','Em tarefa_id','No id da tarefa','Em feito'], answer:1, why:'A chave estrangeira tarefa_id aponta para o id da tarefa relacionada.'}}
 ]},
 {id:'m2', icon:'⌕', color:'purple', title:'Consultas SQL', subtitle:'Busque exatamente o que precisa', desc:'SELECT, filtros e consultas que respondem perguntas reais.', lessons:[
  {id:'l21', title:'SELECT: sua primeira busca', tag:'SQL NA PRÁTICA', time:'9 min', xp:70, type:'lesson', intro:'Quando você precisa saber, por exemplo, “quais tarefas ainda estão pendentes?”, o comando SELECT consulta o banco e retorna exatamente as colunas e linhas que correspondem aos critérios especificados, evitando o desperdício de memória ao trazer apenas o necessário.', code:`SELECT id, titulo, feito\nFROM tarefas;\n\n-- Busca apenas as tarefas não concluídas\nSELECT * FROM tarefas\nWHERE feito = FALSE;`, py:`comando = select(TarefaModel)\nresult = session.execute(comando)\ntarefas = result.scalars().all()`, quiz:{q:'Qual cláusula filtra registros?', opts:['FROM','WHERE','SELECT','FILTER'], answer:1, why:'WHERE define a condição que um registro precisa cumprir para aparecer.'}},
  {id:'l22', title:'Encontrando uma tarefa', tag:'DESAFIO', time:'10 min', xp:80, type:'lesson', intro:'Para abrir os detalhes da tarefa 3, você precisa encontrar um único registro — e lidar com o caso em que ele não existe.', code:`SELECT * FROM tarefas\nWHERE id = 3;\n\nSELECT * FROM comentarios_tarefa\nWHERE tarefa_id = 3;`, py:`comando = select(TarefaModel).where(\n    TarefaModel.id == id\n)\ntarefa = result.scalar_one_or_none()`, quiz:{q:'O que scalar_one_or_none() pode retornar?', opts:['Sempre uma lista','Um modelo ou None','Sempre um erro','A sessão'], answer:1, why:'Ele retorna um único resultado quando existe, ou None quando não encontra.'}}
 ]},
 {id:'m3', icon:'◈', color:'orange', title:'Forjando o ORM', subtitle:'SQLAlchemy sem mistério', desc:'Conecte classes Python às tabelas do banco e mantenha seu código organizado.', lessons:[
  {id:'l31', title:'Model e domínio são diferentes', tag:'ARQUITETURA', time:'12 min', xp:90, type:'lesson', intro:'No projeto, TarefaModel é responsável pela persistência (mapeia a tabela do banco), enquanto TarefaClass contém as regras de negócio (como validar se uma tarefa já está concluída). Essa separação garante que a camada de apresentação (tela) não precise conhecer detalhes de como os dados são armazenados, tornando o código mais modular e fácil de manter.', code:`# model.py → conhece o banco\nclass TarefaModel(Base): ...\n\n# controller.py → conhece regras\nclass Tarefa:\n    def marcar_como_feito(self):\n        if self.feito:\n            raise ValueError("Já concluída")`, py:`nova_tarefa = TarefaClass(\n    titulo=tarefa_modelo.titulo,\n    feito=tarefa_modelo.feito,\n    id=tarefa_modelo.id\n)`, quiz:{q:'Qual classe contém marcar_como_feito()?', opts:['TarefaModel','TarefaClass','ComentarioModel','Base'], answer:1, why:'A regra de negócio vive em TarefaClass, no controller.py.'}},
  {id:'l32', title:'JOIN: conectando histórias', tag:'CONEXÕES', time:'12 min', xp:100, type:'lesson', intro:'Um JOIN reúne a tarefa e seus comentários numa mesma história. É como perguntar: “me conte tudo sobre essa tarefa”.', code:`SELECT t.titulo, c.conteudo\nFROM tarefas t\nLEFT JOIN comentarios_tarefa c\n  ON c.tarefa_id = t.id;`, py:`# evolução conceitual\ntarefa.comentarios`, quiz:{q:'O que representa uma relação 1:N?', opts:['Uma tarefa para um comentário','Várias tarefas para uma tarefa','Uma tarefa para vários comentários','Nenhuma relação'], answer:2, why:'Uma tarefa pode ter N (vários) comentários.'}}
 ]},
 {id:'m4', icon:'↻', color:'green', title:'Transações', subtitle:'Grave com segurança', desc:'INSERT, UPDATE, DELETE e o poder de commit e rollback.', lessons:[
  {id:'l41', title:'Commit ou rollback?', tag:'MÃO NA MASSA', time:'12 min', xp:100, type:'lesson', intro:'Você adicionou uma tarefa, mas ela só existe de verdade quando confirma a transação. Se algo der errado, rollback desfaz o caminho.', code:`INSERT INTO tarefas (titulo, feito)\nVALUES ('Estudar SQL', FALSE);`, py:`session.add(nova_tarefa)\ntry:\n    session.commit()\n    session.refresh(nova_tarefa)\nexcept:\n    session.rollback()`, quiz:{q:'Qual comando confirma uma gravação?', opts:['add()','refresh()','commit()','execute()'], answer:2, why:'commit() confirma a transação e persiste a mudança.'}},
  {id:'l42', title:'A regra de concluir', tag:'REGRA DE NEGÓCIO', time:'10 min', xp:110, type:'lesson', intro:'O botão “Concluir” não deve apenas mudar a tela. Primeiro, a regra do controller verifica se a tarefa já foi concluída.', code:`UPDATE tarefas SET feito = TRUE\nWHERE id = 1;`, py:`if self.feito == True:\n    raise ValueError(\n      "Essa tarefa já está marcada"\n    )\nself.feito = True`, quiz:{q:'Onde deve ficar a regra “não concluir duas vezes”?', opts:['No CSS','No banco apenas','Na regra de negócio','No botão'], answer:2, why:'A regra deve estar no domínio para ser respeitada por qualquer interface.'}}
 ]},
 {id:'m5', icon:'✦', color:'pink', title:'Mini-projeto', subtitle:'Construa o TaskQuest', desc:'Junte tudo: tarefas, comentários, filtros e uma arquitetura limpa.', lessons:[
  {id:'l51', title:'Desafio final: TaskQuest', tag:'PROJETO FINAL', time:'25 min', xp:500, type:'project', intro:'Agora é com você. Planeje uma pequena central de tarefas: liste pendências, conclua tarefas, adicione comentários e trate os erros com mensagens úteis.', code:`# checklist do seu mini-projeto\n1. Listar tarefas\n2. Filtrar por feito\n3. Criar e concluir\n4. Comentar e remover\n5. Tratar tarefas inexistentes`, py:`Tela → serviço → repositório → banco\n\n# controller: regras\n# model: persistência\n# main: orquestração`, quiz:{q:'Qual é o primeiro passo para começar?', opts:['Apagar o model','Listar as tarefas','Ignorar erros','Usar um backend'], answer:1, why:'Comece exibindo os dados: depois evolua para filtros e ações.'}}
 ]},
 {id:'m6', icon:'➕', color:'blue', title:'Operação: CREATE', subtitle:'Dando vida aos dados', desc:'Aprenda a inserir novos registros no banco de dados de forma segura e eficiente.', lessons:[
  {id:'l61', title:'INSERT básico', tag:'SQL ESSENCIAL', time:'10 min', xp:70, type:'lesson', intro:'O comando INSERT adiciona novas linhas a uma tabela. É fundamental garantir que as colunas obrigatórias (NOT NULL) sejam preenchidas.', code:`INSERT INTO tarefas (titulo, feito)\nVALUES ('Aprender SQLAlchemy', FALSE);`, py:`nova_tarefa = TarefaModel(titulo="Aprender SQLAlchemy", feito=False)\nsession.add(nova_tarefa)\nsession.commit()`, quiz:{q:'O que acontece se você esquecer uma coluna NOT NULL no INSERT?', opts:['O banco ignora','O banco gera um erro','O banco coloca um valor aleatório','A linha é criada vazia'], answer:1, why:'Colunas NOT NULL exigem um valor; caso contrário, o banco de dados rejeita a inserção.'}},
  {id:'l62', title:'Criando com Relacionamentos', tag:'AVANÇADO', time:'12 min', xp:80, type:'lesson', intro:'Para criar um comentário, você precisa do ID de uma tarefa existente. Isso garante a integridade referencial do seu banco.', code:`INSERT INTO comentarios_tarefa (tarefa_id, conteudo)\nVALUES (1, 'Lembrar de revisar a documentação');`, py:`comentario = ComentarioModel(tarefa_id=1, conteudo="Lembrar de revisar")\nsession.add(comentario)\nsession.commit()`, quiz:{q:'Por que precisamos do tarefa_id ao criar um comentário?', opts:['Para dar nome ao comentário','Para ligar o comentário a uma tarefa','Para criar a tarefa automaticamente','Não é necessário'], answer:1, why:'O tarefa_id é a chave estrangeira que vincula o comentário à sua tarefa correspondente.'}}
 ]},
 {id:'m7', icon:'📝', color:'yellow', title:'Operação: UPDATE', subtitle:'Evoluindo informações', desc:'Modifique dados existentes sem perder a integridade do sistema.', lessons:[
  {id:'l71', title:'UPDATE e o perigo do WHERE', tag:'ATENÇÃO', time:'10 min', xp:70, type:'lesson', intro:'O comando UPDATE altera registros existentes. CUIDADO: se você esquecer a cláusula WHERE, TODOS os registros da tabela serão alterados!', code:`-- Altera apenas a tarefa 2\nUPDATE tarefas\nSET titulo = 'Título Atualizado'\nWHERE id = 2;`, py:`tarefa = session.get(TarefaModel, 2)\ntarefa.titulo = "Título Atualizado"\nsession.commit()`, quiz:{q:'O que acontece em um UPDATE sem WHERE?', opts:['Nada','Apenas a primeira linha muda','Todas as linhas da tabela são alteradas','O banco deleta a tabela'], answer:2, why:'Sem o WHERE, o SQL não tem filtro e aplica a mudança em cada registro da tabela.'}},
  {id:'l72', title:'Atualizações Parciais', tag:'DICA', time:'10 min', xp:80, type:'lesson', intro:'Muitas vezes queremos mudar apenas um campo (como marcar como feito) sem mexer no restante dos dados da linha.', code:`UPDATE tarefas\nSET feito = TRUE\nWHERE id = 5;`, py:`tarefa = session.get(TarefaModel, 5)\ntarefa.feito = True\nsession.commit()`, quiz:{q:'No SQLAlchemy, como atualizamos um campo?', opts:['Recriando o objeto','Alterando o atributo do objeto e dando commit','Usando o comando delete()','Reiniciando a sessão'], answer:1, why:'O SQLAlchemy monitora as mudanças nos atributos do objeto e as sincroniza no commit.'}}
 ]},
 {id:'m8', icon:'🗑️', color:'red', title:'Operação: DELETE', subtitle:'Limpando a casa', desc:'Remova dados desnecessários e entenda o impacto nas relações.', lessons:[
  {id:'l81', title:'DELETE simples', tag:'SQL ESSENCIAL', time:'10 min', xp:70, type:'lesson', intro:'O comando DELETE remove linhas da tabela. Assim como no UPDATE, o WHERE é crucial para não apagar todo o seu banco de dados.', code:`DELETE FROM tarefas\nWHERE id = 10;`, py:`tarefa = session.get(TarefaModel, 10)\nsession.delete(tarefa)\nsession.commit()`, quiz:{q:'Qual a principal precaução ao usar DELETE?', opts:['Usar SELECT antes','Sempre usar a cláusula WHERE','Fazer backup do disco','Usar letras maiúsculas'], answer:1, why:'Sem o WHERE, todos os registros da tabela serão permanentemente removidos.'}},
  {id:'l82', title:'Delete e Dependências', tag:'INTEGRIDADE', time:'12 min', xp:90, type:'lesson', intro:'Tentar apagar uma tarefa que possui comentários pode gerar um erro de chave estrangeira. Você deve decidir se apaga os comentários primeiro ou usa o "ON DELETE CASCADE".', code:`-- Opção 1: Apagar dependentes primeiro\nDELETE FROM comentarios_tarefa WHERE tarefa_id = 1;\nDELETE FROM tarefas WHERE id = 1;`, py:`# Se configurado com cascade="all, delete"\ntarefa = session.get(TarefaModel, 1)\nsession.delete(tarefa)\nsession.commit() # Apaga a tarefa e seus comentários`, quiz:{q:'O que é o ON DELETE CASCADE?', opts:['Um erro de sintaxe','Um comando para recuperar dados','Uma configuração que apaga automaticamente os filhos ao apagar o pai','Uma forma de renomear tabelas'], answer:2, why:'O CASCADE propaga a exclusão do registro pai para todos os registros filhos vinculados.'}}
 ]}
];
export const badges=[{id:'first',icon:'⚡',title:'Primeiro SELECT',desc:'Completou sua primeira lição'},{id:'streak',icon:'🔥',title:'Constante',desc:'Manteu 3 dias de sequência'},{id:'join',icon:'◈',title:'Mestre do JOIN',desc:'Aprendeu a conectar tabelas'},{id:'finish',icon:'✦',title:'Entrega épica',desc:'Concluiu o mini-projeto'}];